### ISSUE TITLE
你好作者

### ISSUE THREAD

**Issue by chengligen** [qingquanlingyu/KGQA#3]
你好作者，想问一下这个项目，使用大模型回答问题的时候，是根据neo4j或者本地的csv数据回答的吗。我读了本项目和chatrwkv的代码，并没有发现neo4j数据送入大模型里面。

**Comment by qingquanlingyu** [comment]
就是把和问题有关的知识图谱里的相关数据放到大模型prompt里面，让大模型根据这些数据回答问题罢了。具体代码在main.py第305行后

**Comment by chengligen** [comment]
明白了，感谢佬回复！您是我见过回复issue最快的作者！
